### ISSUE TITLE
[images] Utiliser des formats d’images éditables

### ISSUE THREAD

**Issue by mgrzybek** [dnum-mi/CCT-Cloud-Native#13]
Afin d’être plus souple, les images au format PNG devaient être remplacées par des SVG. De plus, pour le moment les sources ne sont pas disponibles.

Peut-être l’occasion de créer des fichiers avec draw.io / diagrams.net (format XML) et d’exporter en SVG / PNG au besoin ?

**Comment by etiquet** [comment]
La production des images est effectuée sur une suite bureautique collaborative (Resana) dans un cadre global de collaboration. Le document source est un équivalent de .ppt et .doc. Une maintenance double est effectuée. Documents sources > markdown. Note : nous n'avons pas identifier la possibilité d'exporter les images en vectoriel ce qui aurait pu augmenter la qualité d'affichage.
