### ISSUE TITLE
cct-cloud-native:Accès équipe Concepteur/developpeur

### ISSUE THREAD

**Issue by sisitototest** [dnum-mi/CCT-Cloud-Native#3]
_Ex14 :Le développeur prend en compte qu’aucune modification n’est effectuée directement en production. Il n’accède pas à l’API kubectl.
Les développeurs n’accèdent pas directement à la plateforme, cet accès s’effectue via une console dédiée et un flux “gitops”. ( via l’usage d’ArgoCD)_

Le developpeur aura-t-il accès à Argocd CLI ou seulement à l'interface graphique en production?
En environnement de dev le developpeur aura-t-il accès à l'API kubectl?

**Comment by etiquet** [comment]
Merci encore. Prises en compte de nombreuses remarques sur cet aspect du CCT. Ces aspects seront suivi en amélioration continue.
