### ISSUE TITLE
Donner une définition de l'objet métier

### ISSUE THREAD

**Issue by CMentG** [dnum-mi/CCT-Cloud-Native#6]
Dans les exigences cct-exigences.md aux lignes
> EX38 	I 	Référencement des objets Métiers dans le catalogue des données Métier du MI

et
> EX45 	I 	Les objets et données métiers doivent systématiquement être exposés via le service d'API management fourni

nous utilisons le terme objet métier. Je n'ai pas trouvé de définition dans cct-glossaire.md.
Pouvons nous ajouter une définition ?

Pour moi dans EX38 il est question de **concept métier** `Représentation mentale abstraite et générale`, c'est la philosophie actuelle du [catalogue de donnée](https://github.com/dnum-mi/cartographie-donnees).
Pour EX45 le terme **objet métier** me semble approprié. Je l’interprète comme `une représentation schématique d'un concept métier`.

Autres références dans [cct-cloud-native.md - L132](https://github.com/dnum-mi/CCT-Cloud-Native/blob/81fd98419641ae3911f62dd901a1f83446160a25/cct-cloud-native.md?plain=1#L132)
> Sur la thématique de l’ouverture et de la circulation de la donnée, le projet est invité à se mettre en conformité avec le volet idoine. Cela concerne notamment le référencement des **objets métiers** dans le référentiel de cartographie des données et la mise à disposition d’une facilité technique d’accès à la donnée basée sur un standard d’échange de type API.

**Comment by etiquet** [comment]
merci pour la suggestion. pris en compte pour objet métier dans le glossaire.
