### ISSUE TITLE
Demande de définitions

### ISSUE THREAD

**Issue by CMentG** [dnum-mi/CCT-Cloud-Native#7]
Je n'ai pas trouvé de définition dans https://raw.githubusercontent.com/dnum-mi/CCT-Cloud-Native/main/images/image8.png pour
- le terme **NFR** (NFR architecture, NFR sécurité).
- le terme **ENT**.

dans https://github.com/dnum-mi/CCT-Cloud-Native/blob/main/images/image5.png
- le terme **CVE**

dans https://raw.githubusercontent.com/dnum-mi/CCT-Cloud-Native/main/images/image3.png
- **SADC** et **SIEM**

Le termes **DSO** n'est pas défini dans le glossaire 😉. Vu une fois dans l'image https://raw.githubusercontent.com/dnum-mi/CCT-Cloud-Native/main/images/image6.png.

I => Important et P => Primordiale ne sont pas en légende du document cct-exigences.md. _Pourquoi utilisé ici un sigle ? De mon point de vu cela n'apporte pas une facilitation à la lecture ._

Pouvez-vous les ajouter ?

**Comment by etiquet** [comment]
merci beaucoup pour ces commentaires !!!
Ils sont pris en compte dans la release alpha v4 )
Les termes I et P sont repris des appellations utilisées dans les marchés publics et utilisés largement par des ministères régaliens.
