### ISSUE TITLE
cct-cloud-native - Texte incomplet dans la section 3

### ISSUE THREAD

**Issue by rhachemi** [dnum-mi/CCT-Cloud-Native#8]
https://github.com/dnum-mi/CCT-Cloud-Native/blob/main/cct-cloud-native.md#des-sp%C3%A9cificit%C3%A9s-%C3%A0-prendre-en-compte-sur-la-topologie-r%C3%A9seau-et-les-ouvertures-de-flux

![Capture](https://user-images.githubusercontent.com/254116/211836504-70a3275f-8db0-44c2-9696-0203125d9862.JPG)

**Comment by etiquet** [comment]
merci corrigé
