### ISSUE TITLE
Eviter de devoir éditer deux fichiers ?

### ISSUE THREAD

**Issue by bzg** [dnum-mi/CCT-Cloud-Native#9]
Le contenu du fichier `cct-glossaire.md` est repris dans `cct-cloud-native.md`: si la reprise peut être automatisée (en créant le second fichier à partir du premier et d'autres ?), cela facilierait la contribution et éviterait de devoir faire les mêmes modifications à deux endroits.

**Comment by etiquet** [comment]
merci. automatisé non... mais supprimé du document  cct-cloud-native.md car redondant

**Comment by bzg** [comment]
> merci. automatisé non... mais supprimé du document cct-cloud-native.md car redondant

D'accord, merci !
